# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: custom_comms.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='custom_comms.proto',
  package='skills',
  syntax='proto3',
  serialized_pb=_b('\n\x12\x63ustom_comms.proto\x12\x06skills\"t\n\x10\x43ustomRpcRequest\x12\r\n\x05utime\x18\x01 \x01(\x03\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x12\n\nrequest_id\x18\x03 \x01(\x03\x12\x0b\n\x03\x61\x63k\x18\x04 \x01(\x08\x12\x11\n\tskill_key\x18\x05 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\x0c\"\x83\x02\n\x11\x43ustomRpcResponse\x12\r\n\x05utime\x18\x01 \x01(\x03\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x12\n\nrequest_id\x18\x03 \x01(\x03\x12\x30\n\x06status\x18\x04 \x01(\x0e\x32 .skills.CustomRpcResponse.Status\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\"z\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x14\n\x0fMODE_NOT_ACTIVE\x10\xe9\x07\x12\x13\n\x0eNO_RPC_HANDLER\x10\xea\x07\x12\x0e\n\tEXCEPTION\x10\xcd\x08\x12\x11\n\x0cINVALID_TYPE\x10\xce\x08\x12\x15\n\x10RESPONSE_TIMEOUT\x10\xd1\x0f\"T\n\x11\x43ustomSkillStatus\x12\r\n\x05utime\x18\x01 \x01(\x03\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x11\n\tskill_key\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x42-\n\x19\x63om.skydio.pbtypes.skillsB\x10\x43ustomCommsProtob\x06proto3')
)



_CUSTOMRPCRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='skills.CustomRpcResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MODE_NOT_ACTIVE', index=1, number=1001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_RPC_HANDLER', index=2, number=1002,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXCEPTION', index=3, number=1101,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_TYPE', index=4, number=1102,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESPONSE_TIMEOUT', index=5, number=2001,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=286,
  serialized_end=408,
)
_sym_db.RegisterEnumDescriptor(_CUSTOMRPCRESPONSE_STATUS)


_CUSTOMRPCREQUEST = _descriptor.Descriptor(
  name='CustomRpcRequest',
  full_name='skills.CustomRpcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='utime', full_name='skills.CustomRpcRequest.utime', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='skills.CustomRpcRequest.version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_id', full_name='skills.CustomRpcRequest.request_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ack', full_name='skills.CustomRpcRequest.ack', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skill_key', full_name='skills.CustomRpcRequest.skill_key', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='skills.CustomRpcRequest.data', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=146,
)


_CUSTOMRPCRESPONSE = _descriptor.Descriptor(
  name='CustomRpcResponse',
  full_name='skills.CustomRpcResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='utime', full_name='skills.CustomRpcResponse.utime', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='skills.CustomRpcResponse.version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_id', full_name='skills.CustomRpcResponse.request_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='skills.CustomRpcResponse.status', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='skills.CustomRpcResponse.data', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CUSTOMRPCRESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=408,
)


_CUSTOMSKILLSTATUS = _descriptor.Descriptor(
  name='CustomSkillStatus',
  full_name='skills.CustomSkillStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='utime', full_name='skills.CustomSkillStatus.utime', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='skills.CustomSkillStatus.version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skill_key', full_name='skills.CustomSkillStatus.skill_key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='skills.CustomSkillStatus.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=410,
  serialized_end=494,
)

_CUSTOMRPCRESPONSE.fields_by_name['status'].enum_type = _CUSTOMRPCRESPONSE_STATUS
_CUSTOMRPCRESPONSE_STATUS.containing_type = _CUSTOMRPCRESPONSE
DESCRIPTOR.message_types_by_name['CustomRpcRequest'] = _CUSTOMRPCREQUEST
DESCRIPTOR.message_types_by_name['CustomRpcResponse'] = _CUSTOMRPCRESPONSE
DESCRIPTOR.message_types_by_name['CustomSkillStatus'] = _CUSTOMSKILLSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CustomRpcRequest = _reflection.GeneratedProtocolMessageType('CustomRpcRequest', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMRPCREQUEST,
  __module__ = 'custom_comms_pb2'
  # @@protoc_insertion_point(class_scope:skills.CustomRpcRequest)
  ))
_sym_db.RegisterMessage(CustomRpcRequest)

CustomRpcResponse = _reflection.GeneratedProtocolMessageType('CustomRpcResponse', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMRPCRESPONSE,
  __module__ = 'custom_comms_pb2'
  # @@protoc_insertion_point(class_scope:skills.CustomRpcResponse)
  ))
_sym_db.RegisterMessage(CustomRpcResponse)

CustomSkillStatus = _reflection.GeneratedProtocolMessageType('CustomSkillStatus', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMSKILLSTATUS,
  __module__ = 'custom_comms_pb2'
  # @@protoc_insertion_point(class_scope:skills.CustomSkillStatus)
  ))
_sym_db.RegisterMessage(CustomSkillStatus)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\031com.skydio.pbtypes.skillsB\020CustomCommsProto'))
# @@protoc_insertion_point(module_scope)
