# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: skybus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='skybus.proto',
  package='skybus',
  syntax='proto3',
  serialized_options=_b('\n\031com.skydio.pbtypes.skybusB\tSyncProto'),
  serialized_pb=_b('\n\x0cskybus.proto\x12\x06skybus\"6\n\tClockSync\x12\x11\n\tmaster_t0\x18\x02 \x01(\x10\x12\x10\n\x08slave_t1\x18\x03 \x01(\x10J\x04\x08\x01\x10\x02\";\n\x11SubscribedChannel\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x15\n\rdownsample_dt\x18\x02 \x01(\x02\"u\n\x15SubscribedChannelList\x12\r\n\x05utime\x18\x01 \x01(\x03\x12\r\n\x05nonce\x18\x02 \x01(\x07\x12+\n\x08\x63hannels\x18\x03 \x03(\x0b\x32\x19.skybus.SubscribedChannel\x12\x11\n\tclient_id\x18\x04 \x01(\t\"/\n\x0fSubscriptionAck\x12\r\n\x05utime\x18\x01 \x01(\x03\x12\r\n\x05nonce\x18\x02 \x01(\x07\x42&\n\x19\x63om.skydio.pbtypes.skybusB\tSyncProtob\x06proto3')
)




_CLOCKSYNC = _descriptor.Descriptor(
  name='ClockSync',
  full_name='skybus.ClockSync',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='master_t0', full_name='skybus.ClockSync.master_t0', index=0,
      number=2, type=16, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slave_t1', full_name='skybus.ClockSync.slave_t1', index=1,
      number=3, type=16, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=78,
)


_SUBSCRIBEDCHANNEL = _descriptor.Descriptor(
  name='SubscribedChannel',
  full_name='skybus.SubscribedChannel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='skybus.SubscribedChannel.channel', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='downsample_dt', full_name='skybus.SubscribedChannel.downsample_dt', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=139,
)


_SUBSCRIBEDCHANNELLIST = _descriptor.Descriptor(
  name='SubscribedChannelList',
  full_name='skybus.SubscribedChannelList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='utime', full_name='skybus.SubscribedChannelList.utime', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='skybus.SubscribedChannelList.nonce', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channels', full_name='skybus.SubscribedChannelList.channels', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='skybus.SubscribedChannelList.client_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=258,
)


_SUBSCRIPTIONACK = _descriptor.Descriptor(
  name='SubscriptionAck',
  full_name='skybus.SubscriptionAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='utime', full_name='skybus.SubscriptionAck.utime', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='skybus.SubscriptionAck.nonce', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=307,
)

_SUBSCRIBEDCHANNELLIST.fields_by_name['channels'].message_type = _SUBSCRIBEDCHANNEL
DESCRIPTOR.message_types_by_name['ClockSync'] = _CLOCKSYNC
DESCRIPTOR.message_types_by_name['SubscribedChannel'] = _SUBSCRIBEDCHANNEL
DESCRIPTOR.message_types_by_name['SubscribedChannelList'] = _SUBSCRIBEDCHANNELLIST
DESCRIPTOR.message_types_by_name['SubscriptionAck'] = _SUBSCRIPTIONACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClockSync = _reflection.GeneratedProtocolMessageType('ClockSync', (_message.Message,), dict(
  DESCRIPTOR = _CLOCKSYNC,
  __module__ = 'skybus_pb2'
  # @@protoc_insertion_point(class_scope:skybus.ClockSync)
  ))
_sym_db.RegisterMessage(ClockSync)

SubscribedChannel = _reflection.GeneratedProtocolMessageType('SubscribedChannel', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIBEDCHANNEL,
  __module__ = 'skybus_pb2'
  # @@protoc_insertion_point(class_scope:skybus.SubscribedChannel)
  ))
_sym_db.RegisterMessage(SubscribedChannel)

SubscribedChannelList = _reflection.GeneratedProtocolMessageType('SubscribedChannelList', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIBEDCHANNELLIST,
  __module__ = 'skybus_pb2'
  # @@protoc_insertion_point(class_scope:skybus.SubscribedChannelList)
  ))
_sym_db.RegisterMessage(SubscribedChannelList)

SubscriptionAck = _reflection.GeneratedProtocolMessageType('SubscriptionAck', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIPTIONACK,
  __module__ = 'skybus_pb2'
  # @@protoc_insertion_point(class_scope:skybus.SubscriptionAck)
  ))
_sym_db.RegisterMessage(SubscriptionAck)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
