"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class MatrixXi(object):
    __slots__ = ["rows", "data_sz", "data"]

    def __init__(self,
                 rows=0,
                 data_sz=0,
                 data=None,
                 _skip_initialize=False):
        """ If _skip_initialize is True, all other constructor arguments are ignored """
        if _skip_initialize: return
        self.rows = rows
        self.data_sz = data_sz
        self.data = [] if data is None else data

    @staticmethod
    def _skytype_meta():
        return dict(
            type='struct',
            package='eigen_lcm',
            name='MatrixXi',
        )

    @classmethod
    def _default(cls):
        return cls()

    def __repr__(self):
        return 'lcmtypes.eigen_lcm.MatrixXi({})'.format(
            ', '.join('{}={}'.format(name, repr(getattr(self, name))) for name in self.__slots__))

    def encode(self):
        buf = BytesIO()
        buf.write(MatrixXi._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ii", self.rows, self.data_sz))
        buf.write(struct.pack('>%di' % self.data_sz, *self.data[:self.data_sz]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != MatrixXi._get_packed_fingerprint():
            raise ValueError("Decode error")
        return MatrixXi._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = MatrixXi(_skip_initialize=True)
        self.rows, self.data_sz = struct.unpack(">ii", buf.read(8))
        self.data = struct.unpack('>%di' % self.data_sz, buf.read(self.data_sz * 4))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if MatrixXi in parents: return 0
        tmphash = (0xa8245e97d27287f8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if MatrixXi._packed_fingerprint is None:
            MatrixXi._packed_fingerprint = struct.pack(">Q", MatrixXi._get_hash_recursive([]))
        return MatrixXi._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)
