"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class Quaternionf(object):
    __slots__ = ["xyzw"]

    def __init__(self,
                 xyzw=None,
                 _skip_initialize=False):
        """ If _skip_initialize is True, all other constructor arguments are ignored """
        if _skip_initialize: return
        self.xyzw = [ 0.0 for dim0 in range(4) ] if xyzw is None else xyzw

    @staticmethod
    def _skytype_meta():
        return dict(
            type='struct',
            package='eigen_lcm',
            name='Quaternionf',
        )

    @classmethod
    def _default(cls):
        return cls()

    def __repr__(self):
        return 'lcmtypes.eigen_lcm.Quaternionf({})'.format(
            ', '.join('{}={}'.format(name, repr(getattr(self, name))) for name in self.__slots__))

    def encode(self):
        buf = BytesIO()
        buf.write(Quaternionf._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>4f', *self.xyzw[:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Quaternionf._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Quaternionf._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Quaternionf(_skip_initialize=True)
        self.xyzw = list(struct.unpack('>4f', buf.read(16)))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if Quaternionf in parents: return 0
        tmphash = (0x5c785266f6c9245a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Quaternionf._packed_fingerprint is None:
            Quaternionf._packed_fingerprint = struct.pack(">Q", Quaternionf._get_hash_recursive([]))
        return Quaternionf._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)
