"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class Vector4f(object):
    __slots__ = ["data"]

    def __init__(self,
                 data=None,
                 _skip_initialize=False):
        """ If _skip_initialize is True, all other constructor arguments are ignored """
        if _skip_initialize: return
        self.data = [ 0.0 for dim0 in range(4) ] if data is None else data

    @staticmethod
    def _skytype_meta():
        return dict(
            type='struct',
            package='eigen_lcm',
            name='Vector4f',
        )

    @classmethod
    def _default(cls):
        return cls()

    def __repr__(self):
        return 'lcmtypes.eigen_lcm.Vector4f({})'.format(
            ', '.join('{}={}'.format(name, repr(getattr(self, name))) for name in self.__slots__))

    def encode(self):
        buf = BytesIO()
        buf.write(Vector4f._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>4f', *self.data[:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Vector4f._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Vector4f._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Vector4f(_skip_initialize=True)
        self.data = list(struct.unpack('>4f', buf.read(16)))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if Vector4f in parents: return 0
        tmphash = (0x5c782a36eaf5245a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Vector4f._packed_fingerprint is None:
            Vector4f._packed_fingerprint = struct.pack(">Q", Vector4f._get_hash_recursive([]))
        return Vector4f._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)
