"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import skydio.lcmtypes.eigen_lcm._Vector3f

import skydio.lcmtypes.eigen_lcm._Vector3f

class imu_meas_t(object):
    __slots__ = ["utime", "angular_velocity", "acceleration"]

    def __init__(self,
                 utime=0,
                 angular_velocity=None,
                 acceleration=None,
                 _skip_initialize=False):
        """ If _skip_initialize is True, all other constructor arguments are ignored """
        if _skip_initialize: return
        self.utime = utime
        # inertial measurements in the coordinate frame of the IMU
        self.angular_velocity = skydio.lcmtypes.eigen_lcm.Vector3f._default() if angular_velocity is None else angular_velocity
        self.acceleration = skydio.lcmtypes.eigen_lcm.Vector3f._default() if acceleration is None else acceleration

    @staticmethod
    def _skytype_meta():
        return dict(
            type='struct',
            package='common',
            name='imu_meas_t',
        )

    @classmethod
    def _default(cls):
        return cls()

    def __repr__(self):
        return 'skydio.lcmtypes.common.imu_meas_t({})'.format(
            ', '.join('{}={}'.format(name, repr(getattr(self, name))) for name in self.__slots__))

    def encode(self):
        buf = BytesIO()
        buf.write(imu_meas_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        assert self.angular_velocity._get_packed_fingerprint() == skydio.lcmtypes.eigen_lcm.Vector3f._get_packed_fingerprint()
        self.angular_velocity._encode_one(buf)
        assert self.acceleration._get_packed_fingerprint() == skydio.lcmtypes.eigen_lcm.Vector3f._get_packed_fingerprint()
        self.acceleration._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != imu_meas_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return imu_meas_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = imu_meas_t(_skip_initialize=True)
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.angular_velocity = skydio.lcmtypes.eigen_lcm.Vector3f._decode_one(buf)
        self.acceleration = skydio.lcmtypes.eigen_lcm.Vector3f._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if imu_meas_t in parents: return 0
        newparents = parents + [imu_meas_t]
        tmphash = (0x207b01668fe8090+ skydio.lcmtypes.eigen_lcm.Vector3f._get_hash_recursive(newparents)+ skydio.lcmtypes.eigen_lcm.Vector3f._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if imu_meas_t._packed_fingerprint is None:
            imu_meas_t._packed_fingerprint = struct.pack(">Q", imu_meas_t._get_hash_recursive([]))
        return imu_meas_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)
