"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class air_density_t(object):
    __slots__ = ["utime", "air_density"]

    def __init__(self,
                 utime=0,
                 air_density=0.0,
                 _skip_initialize=False):
        """ If _skip_initialize is True, all other constructor arguments are ignored """
        if _skip_initialize: return
        self.utime = utime
        self.air_density = air_density

    @staticmethod
    def _skytype_meta():
        return dict(
            type='struct',
            package='dynamics_model',
            name='air_density_t',
        )

    @classmethod
    def _default(cls):
        return cls()

    def __repr__(self):
        return 'lcmtypes.dynamics_model.air_density_t({})'.format(
            ', '.join('{}={}'.format(name, repr(getattr(self, name))) for name in self.__slots__))

    def encode(self):
        buf = BytesIO()
        buf.write(air_density_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qf", self.utime, self.air_density))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != air_density_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return air_density_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = air_density_t(_skip_initialize=True)
        self.utime, self.air_density = struct.unpack(">qf", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if air_density_t in parents: return 0
        tmphash = (0xd9d6dcd40f526886) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if air_density_t._packed_fingerprint is None:
            air_density_t._packed_fingerprint = struct.pack(">Q", air_density_t._get_hash_recursive([]))
        return air_density_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)
