"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import skydio.lcmtypes.body._wrench_t

import skydio.lcmtypes.body._wrench_t

import skydio.lcmtypes.body._wrench_t

class wind_wrenches_t(object):
    __slots__ = ["utime", "in_contact", "rotor_rates_valid", "predicted_aero_wrench", "residual_wrench", "contact_wrench"]

    def __init__(self,
                 utime=0,
                 in_contact=False,
                 rotor_rates_valid=False,
                 predicted_aero_wrench=None,
                 residual_wrench=None,
                 contact_wrench=None,
                 _skip_initialize=False):
        """ If _skip_initialize is True, all other constructor arguments are ignored """
        if _skip_initialize: return
        self.utime = utime
        self.in_contact = in_contact
        self.rotor_rates_valid = rotor_rates_valid
        self.predicted_aero_wrench = skydio.lcmtypes.body.wrench_t._default() if predicted_aero_wrench is None else predicted_aero_wrench
        self.residual_wrench = skydio.lcmtypes.body.wrench_t._default() if residual_wrench is None else residual_wrench
        self.contact_wrench = skydio.lcmtypes.body.wrench_t._default() if contact_wrench is None else contact_wrench

    @staticmethod
    def _skytype_meta():
        return dict(
            type='struct',
            package='dynamics_model',
            name='wind_wrenches_t',
        )

    @classmethod
    def _default(cls):
        return cls()

    def __repr__(self):
        return 'lcmtypes.dynamics_model.wind_wrenches_t({})'.format(
            ', '.join('{}={}'.format(name, repr(getattr(self, name))) for name in self.__slots__))

    def encode(self):
        buf = BytesIO()
        buf.write(wind_wrenches_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qbb", self.utime, self.in_contact, self.rotor_rates_valid))
        assert self.predicted_aero_wrench._get_packed_fingerprint() == skydio.lcmtypes.body.wrench_t._get_packed_fingerprint()
        self.predicted_aero_wrench._encode_one(buf)
        assert self.residual_wrench._get_packed_fingerprint() == skydio.lcmtypes.body.wrench_t._get_packed_fingerprint()
        self.residual_wrench._encode_one(buf)
        assert self.contact_wrench._get_packed_fingerprint() == skydio.lcmtypes.body.wrench_t._get_packed_fingerprint()
        self.contact_wrench._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != wind_wrenches_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return wind_wrenches_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = wind_wrenches_t(_skip_initialize=True)
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.in_contact = bool(struct.unpack('b', buf.read(1))[0])
        self.rotor_rates_valid = bool(struct.unpack('b', buf.read(1))[0])
        self.predicted_aero_wrench = skydio.lcmtypes.body.wrench_t._decode_one(buf)
        self.residual_wrench = skydio.lcmtypes.body.wrench_t._decode_one(buf)
        self.contact_wrench = skydio.lcmtypes.body.wrench_t._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if wind_wrenches_t in parents: return 0
        newparents = parents + [wind_wrenches_t]
        tmphash = (0xe3c8af96907ef823+ skydio.lcmtypes.body.wrench_t._get_hash_recursive(newparents)+ skydio.lcmtypes.body.wrench_t._get_hash_recursive(newparents)+ skydio.lcmtypes.body.wrench_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if wind_wrenches_t._packed_fingerprint is None:
            wind_wrenches_t._packed_fingerprint = struct.pack(">Q", wind_wrenches_t._get_hash_recursive([]))
        return wind_wrenches_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)
