"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import skydio.lcmtypes.eigen_lcm._Vector3f

import skydio.lcmtypes.eigen_lcm._Matrix3f

import skydio.lcmtypes.eigen_lcm._Vector3f

class wind_t(object):
    __slots__ = ["converged", "estimate", "covariance", "raw"]

    def __init__(self,
                 converged=False,
                 estimate=None,
                 covariance=None,
                 raw=None,
                 _skip_initialize=False):
        """ If _skip_initialize is True, all other constructor arguments are ignored """
        if _skip_initialize: return
        self.converged = converged
        self.estimate = skydio.lcmtypes.eigen_lcm.Vector3f._default() if estimate is None else estimate
        self.covariance = skydio.lcmtypes.eigen_lcm.Matrix3f._default() if covariance is None else covariance
        self.raw = skydio.lcmtypes.eigen_lcm.Vector3f._default() if raw is None else raw

    @staticmethod
    def _skytype_meta():
        return dict(
            type='struct',
            package='dynamics_model',
            name='wind_t',
        )

    @classmethod
    def _default(cls):
        return cls()

    def __repr__(self):
        return 'lcmtypes.dynamics_model.wind_t({})'.format(
            ', '.join('{}={}'.format(name, repr(getattr(self, name))) for name in self.__slots__))

    def encode(self):
        buf = BytesIO()
        buf.write(wind_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.converged))
        assert self.estimate._get_packed_fingerprint() == skydio.lcmtypes.eigen_lcm.Vector3f._get_packed_fingerprint()
        self.estimate._encode_one(buf)
        assert self.covariance._get_packed_fingerprint() == skydio.lcmtypes.eigen_lcm.Matrix3f._get_packed_fingerprint()
        self.covariance._encode_one(buf)
        assert self.raw._get_packed_fingerprint() == skydio.lcmtypes.eigen_lcm.Vector3f._get_packed_fingerprint()
        self.raw._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != wind_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return wind_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = wind_t(_skip_initialize=True)
        self.converged = bool(struct.unpack('b', buf.read(1))[0])
        self.estimate = skydio.lcmtypes.eigen_lcm.Vector3f._decode_one(buf)
        self.covariance = skydio.lcmtypes.eigen_lcm.Matrix3f._decode_one(buf)
        self.raw = skydio.lcmtypes.eigen_lcm.Vector3f._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if wind_t in parents: return 0
        newparents = parents + [wind_t]
        tmphash = (0x21d1ab2b5b4de883+ skydio.lcmtypes.eigen_lcm.Vector3f._get_hash_recursive(newparents)+ skydio.lcmtypes.eigen_lcm.Matrix3f._get_hash_recursive(newparents)+ skydio.lcmtypes.eigen_lcm.Vector3f._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if wind_t._packed_fingerprint is None:
            wind_t._packed_fingerprint = struct.pack(">Q", wind_t._get_hash_recursive([]))
        return wind_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)
