"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import skydio.lcmtypes.dynamics_model._wind_t

class wind_stamped_t(object):
    __slots__ = ["utime", "wind"]

    def __init__(self,
                 utime=0,
                 wind=None,
                 _skip_initialize=False):
        """ If _skip_initialize is True, all other constructor arguments are ignored """
        if _skip_initialize: return
        self.utime = utime
        self.wind = skydio.lcmtypes.dynamics_model.wind_t._default() if wind is None else wind

    @staticmethod
    def _skytype_meta():
        return dict(
            type='struct',
            package='dynamics_model',
            name='wind_stamped_t',
        )

    @classmethod
    def _default(cls):
        return cls()

    def __repr__(self):
        return 'lcmtypes.dynamics_model.wind_stamped_t({})'.format(
            ', '.join('{}={}'.format(name, repr(getattr(self, name))) for name in self.__slots__))

    def encode(self):
        buf = BytesIO()
        buf.write(wind_stamped_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        assert self.wind._get_packed_fingerprint() == skydio.lcmtypes.dynamics_model.wind_t._get_packed_fingerprint()
        self.wind._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != wind_stamped_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return wind_stamped_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = wind_stamped_t(_skip_initialize=True)
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.wind = skydio.lcmtypes.dynamics_model.wind_t._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if wind_stamped_t in parents: return 0
        newparents = parents + [wind_stamped_t]
        tmphash = (0x2768526a27ac72fa+ skydio.lcmtypes.dynamics_model.wind_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if wind_stamped_t._packed_fingerprint is None:
            wind_stamped_t._packed_fingerprint = struct.pack(">Q", wind_stamped_t._get_hash_recursive([]))
        return wind_stamped_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)
