"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import skydio.lcmtypes.body._wrench_t

import skydio.lcmtypes.body._wrench_t

import skydio.lcmtypes.body._wrench_t

import skydio.lcmtypes.body._wrench_t

class wrenches_t(object):
    __slots__ = ["utime", "total_wrench", "rotor_wrench", "aero_wrench", "external_wrench"]

    def __init__(self,
                 utime=0,
                 total_wrench=None,
                 rotor_wrench=None,
                 aero_wrench=None,
                 external_wrench=None,
                 _skip_initialize=False):
        """ If _skip_initialize is True, all other constructor arguments are ignored """
        if _skip_initialize: return
        self.utime = utime
        self.total_wrench = skydio.lcmtypes.body.wrench_t._default() if total_wrench is None else total_wrench
        self.rotor_wrench = skydio.lcmtypes.body.wrench_t._default() if rotor_wrench is None else rotor_wrench
        self.aero_wrench = skydio.lcmtypes.body.wrench_t._default() if aero_wrench is None else aero_wrench
        self.external_wrench = skydio.lcmtypes.body.wrench_t._default() if external_wrench is None else external_wrench

    @staticmethod
    def _skytype_meta():
        return dict(
            type='struct',
            package='dynamics_model',
            name='wrenches_t',
        )

    @classmethod
    def _default(cls):
        return cls()

    def __repr__(self):
        return 'lcmtypes.dynamics_model.wrenches_t({})'.format(
            ', '.join('{}={}'.format(name, repr(getattr(self, name))) for name in self.__slots__))

    def encode(self):
        buf = BytesIO()
        buf.write(wrenches_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        assert self.total_wrench._get_packed_fingerprint() == skydio.lcmtypes.body.wrench_t._get_packed_fingerprint()
        self.total_wrench._encode_one(buf)
        assert self.rotor_wrench._get_packed_fingerprint() == skydio.lcmtypes.body.wrench_t._get_packed_fingerprint()
        self.rotor_wrench._encode_one(buf)
        assert self.aero_wrench._get_packed_fingerprint() == skydio.lcmtypes.body.wrench_t._get_packed_fingerprint()
        self.aero_wrench._encode_one(buf)
        assert self.external_wrench._get_packed_fingerprint() == skydio.lcmtypes.body.wrench_t._get_packed_fingerprint()
        self.external_wrench._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != wrenches_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return wrenches_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = wrenches_t(_skip_initialize=True)
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.total_wrench = skydio.lcmtypes.body.wrench_t._decode_one(buf)
        self.rotor_wrench = skydio.lcmtypes.body.wrench_t._decode_one(buf)
        self.aero_wrench = skydio.lcmtypes.body.wrench_t._decode_one(buf)
        self.external_wrench = skydio.lcmtypes.body.wrench_t._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if wrenches_t in parents: return 0
        newparents = parents + [wrenches_t]
        tmphash = (0x9859ae53e18e810a+ skydio.lcmtypes.body.wrench_t._get_hash_recursive(newparents)+ skydio.lcmtypes.body.wrench_t._get_hash_recursive(newparents)+ skydio.lcmtypes.body.wrench_t._get_hash_recursive(newparents)+ skydio.lcmtypes.body.wrench_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if wrenches_t._packed_fingerprint is None:
            wrenches_t._packed_fingerprint = struct.pack(">Q", wrenches_t._get_hash_recursive([]))
        return wrenches_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)
